[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]

[tool.ruff]
select = [
    "E",
    "F",
    "I",
    "A",
    "COM",
    "ALL",
    "ISC",
    "RET",
    "Q",
    "N",
]

[tool.ruff.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.pep8-naming]
ignore-names = ["setUp", "tearDown", "setUpClass", "tearDownClass"]



