[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "parametrize>=0.1.1",
    "sentence-transformers>=5.1.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.0",
]

[tool.ruff.lint]
select = [ "E", "F", "I", "A", "ANN", "COM", "ISC", "RET", "Q", "N" ]

ignore = [
    "D203",
    "D213",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.lint.pep8-naming]
ignore-names = ["setUp", "tearDown", "setUpClass", "tearDownClass"]



